language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: DEPS=lowest
    - php: 7.0
      env: DEPS=latest
    - php: 7.1
      env: DEPS=lowest
    - php: 7.1
      env: DEPS=latest

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --prefer-dist --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest ; fi

script:
    - vendor/bin/phpunit
